# Generated by Django 5.0.6 on 2024-07-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('actions', models.CharField(max_length=225)),
                ('image', models.ImageField(default='default.', upload_to='book_images')),
            ],
        ),
    ]
